[phases.setup]
nixPkgs = ["nodejs_22", "openssl"]

[phases.install]
cmds = ["npm install --ignore-scripts"]

[phases.build]
cmds = ["npx prisma generate", "npx next build"]

[start]
cmd = "npx next start -H 0.0.0.0 -p 3000"
